version: '3.3'
services: 
  postgres:
    image: 'postgres:13-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - ./datadir:/var/lib/postgresql/data
  # redis:
  #   image: 'redis:latest'
  #   restart: always
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:80'


