export * as mutations from './Mutations'
export * as query from './Query' 
export * as Post from './posts'
export * as Cruise from './cruise'
export * as Comment from './comment'
export * as Challenge from './challenge'
export * as User from './user'
