export * as Mutation from './Mutation'
export * as Query from './Query'
export * as Post from './posts'
export * as Cruise from './cruise'
export * as Comment from './comment'
export * as Challenge from './challenge'
export * as User from './user'
